### ISSUE TITLE
How to build benchmark1?

### ISSUE THREAD

**Issue by LambertZhaglog** [SkywalkingTest/Agent-Benchmarks#6]
I'm newer to Java. 

Any dependency lib, build tools or framework to build these benchmarks? 

Much Thanks if you can provide build script or Java executable!

**Comment by wu-sheng** [comment]
The source codes have been provided in each case. Generally, they are mocking libraries for the agent rather than really calling a library because it could be mismeasured due to remote server performance limitations.

Also, we don't maintain this anymore. SkyWalking has hundreds of users in prod, some are handling 10b+ trace segments per day. 
This is just a simple reference now, if you want to run a performance benchmark, you could set one on your own services.
